@startuml


!define STYLE_DEFAULT_WORK #ffffff
!define STYLE_DEFAULT_WORK_LITE #LightBlue

!define STYLE_DEFAULT_SCA #DarkGreen
!define STYLE_DEFAULT_SCA_LITE #LightGreen

!define STYLE_DEFAULT_EXTERNAL #Orange
!define STYLE_DEFAULT_EXTERNAL_LITE #LightOrange

!define STYLE_DEFAULT_BORDER #Black



skinparam SequenceGroupBodyBackgroundColor transparent 
skinparam ParticipantPadding 0
skinparam BoxPadding 10
skinparam shadowing false
skinparam roundcorner 20
skinparam BackgroundColor STYLE_DEFAULT_WORK
skinparam ArrowColor STYLE_DEFAULT_BORDER



skinparam default {
    BackgroundColor STYLE_DEFAULT_WORK_LITE
    BackgroundColor<<SCA>> #STYLE_DEFAULT_SCA_LITE
    BackgroundColor<<External>> #STYLE_DEFAULT_EXTERNAL_LITE
    BorderColor STYLE_DEFAULT_BORDER
}

skinparam SequenceBox {
    BackgroundColor STYLE_DEFAULT_WORK_LITE
    BackgroundColor<<SCA>> #STYLE_DEFAULT_SCA_LITE
    BackgroundColor<<External>> #STYLE_DEFAULT_EXTERNAL_LITE
    BorderColor STYLE_DEFAULT_BORDER
}

skinparam Note {
    BackgroundColor #GOLD
    BorderColor STYLE_DEFAULT_BORDER
    FontColor STYLE_DEFAULT_BORDER
}

skinparam Actor {
    BackgroundColor STYLE_DEFAULT_WORK_LITE
    BackgroundColor<<SCA>> #STYLE_DEFAULT_SCA_LITE
    BackgroundColor<<External>> #STYLE_DEFAULT_EXTERNAL_LITE
    BorderColor STYLE_DEFAULT_BORDER
}

skinparam Node {
    BackgroundColor STYLE_DEFAULT_WORK_LITE
    BackgroundColor<<SCA>> #STYLE_DEFAULT_SCA_LITE
    BackgroundColor<<External>> #STYLE_DEFAULT_EXTERNAL_LITE
    BorderColor STYLE_DEFAULT_BORDER
}

skinparam Component {
    BackgroundColor STYLE_DEFAULT_WORK
    BackgroundColor<<SCA>> #STYLE_DEFAULT_SCA
    BackgroundColor<<External>> #STYLE_DEFAULT_EXTERNAL
    BorderColor STYLE_DEFAULT_BORDER
    FontColor STYLE_DEFAULT_WORK
}

skinparam  Activity {
    'BackgroundColor #007ac9
    BackgroundColor STYLE_DEFAULT_WORK_LITE
    BackgroundColor<<SCA>> #STYLE_DEFAULT_SCA_LITE
    BackgroundColor<<External>> #STYLE_DEFAULT_EXTERNAL_LITE

    'DiamondBackgroundColor #007ac9
    DiamondBackgroundColor STYLE_DEFAULT_WORK_LITE
    DiamondBackgroundColor<<SCA>> #STYLE_DEFAULT_SCA_LITE
    DiamondBackgroundColor<<External>> #STYLE_DEFAULT_EXTERNAL_LITE

    BorderColor STYLE_DEFAULT_BORDER
    FontColor STYLE_DEFAULT_WORK
    DiamondBorderColor  STYLE_DEFAULT_BORDER
    DiamondFontColor STYLE_DEFAULT_WORK

}

skinparam Interface {
    BackgroundColor STYLE_DEFAULT_WORK_LITE
    BackgroundColor<<SCA>> #STYLE_DEFAULT_SCA_LITE
    BackgroundColor<<External>> #STYLE_DEFAULT_EXTERNAL_LITE
    BorderColor STYLE_DEFAULT_BORDER
}
skinparam Usecase {
    BackgroundColor STYLE_DEFAULT_WORK_LITE
    BackgroundColor<<SCA>> #STYLE_DEFAULT_SCA_LITE
    BackgroundColor<<External>> #STYLE_DEFAULT_EXTERNAL_LITE
    BorderColor STYLE_DEFAULT_BORDER
}

skinparam Rectangle {
    BackgroundColor STYLE_DEFAULT_WORK_LITE
    BackgroundColor<<SCA>> #STYLE_DEFAULT_SCA_LITE
    BackgroundColor<<External>> #STYLE_DEFAULT_EXTERNAL_LITE
    BorderColor STYLE_DEFAULT_BORDER
}

skinparam Partition {
    BackgroundColor STYLE_DEFAULT_WORK_LITE
    BackgroundColor<<SCA>> #STYLE_DEFAULT_SCA_LITE
    BackgroundColor<<External>> #STYLE_DEFAULT_EXTERNAL_LITE
}
skinparam Package {
    BackgroundColor STYLE_DEFAULT_WORK_LITE
    BackgroundColor<<SCA>> #STYLE_DEFAULT_SCA_LITE
    BackgroundColor<<External>> #STYLE_DEFAULT_EXTERNAL_LITE
    BorderColor STYLE_DEFAULT_BORDER
}

skinparam Queue {
    BackgroundColor STYLE_DEFAULT_WORK_LITE
    BackgroundColor<<SCA>> #STYLE_DEFAULT_SCA_LITE
    BackgroundColor<<External>> #STYLE_DEFAULT_EXTERNAL_LITE
    BorderColor STYLE_DEFAULT_BORDER
}

skinparam Database {
    BackgroundColor STYLE_DEFAULT_WORK_LITE
    BackgroundColor<<SCA>> #STYLE_DEFAULT_SCA_LITE
    BackgroundColor<<External>> #STYLE_DEFAULT_EXTERNAL_LITE
    BorderColor STYLE_DEFAULT_BORDER
}

skinparam Participant {
    BackgroundColor STYLE_DEFAULT_WORK_LITE
    BackgroundColor<<SCA>> #STYLE_DEFAULT_SCA_LITE
    BackgroundColor<<External>> #STYLE_DEFAULT_EXTERNAL_LITE

    BorderColor STYLE_DEFAULT_BORDER
    FontColor STYLE_DEFAULT_WORK
}

skinparam Sequence {
    'LifeLineBorderColor #007ac9
}

@enduml
