@startuml

!pragma teoz true


!definelong ReqResp(px, py, req, resp)
px -> py +: req
py -> px -: resp
!enddefinelong


!definelong ReqProxy(px, py, pz, req, resp)
px <-> py : req::resp
&py <-> pz : <proxying> req::resp


!definelong ReqProxy4(pw, px, py, pz, req, resp)
pw <-> py : req::resp
&px <-> py : <proxying> req::resp
&py <-> pz : <proxying> req::resp

/'  if no teoz available
ReqResp(px, py, req, resp)
px -> py +: req
py -> pz +: <proxying> req
pz -> py -: resp
py -> px -: resp
'/
!enddefinelong


!definelong Redirect(x, y, z, req, resp)
x -> y +: req
y -> y : generate resp
y -> x -: redirect(resp)
x -> z +: redirect(resp)
!enddefinelong

@enduml
